version: '3.6'
services:
  wphdtfows-oss-sau:
    build:
      dockerfile: Dockerfile.wphdtfows-oss
      context: .
    image: ilonghi/wphdtfows-oss:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
    hostname: wphdtfows-oss
    container_name: wphdtfows-oss-sau
    networks:
      - wphdtfo-net
    command:
      - /bin/bash
      - -c
      - source ~/.bash_profile; session_audit_upload.sh -n

networks:
  wphdtfo-net:
    external:
      name: wphdtfo-net

volumes:
  wphdtfo-art-repository-dsk:
    external: true
    name: wphdtfo-art-repository-dsk
  wphdtfo-repository-dsk:
    external: true
    name: wphdtfo-repository-dsk
