version: '3.6'
services:
  wphdtfo-memcached:
    image: memcached:1.5.6-alpine
    hostname: wphdtfo-memcached
    container_name: wphdtfo-memcached
    networks:
      - wphdtfo-net
  wphdtfo-web-proxy:
    image: ilonghi/wphdtfo-web-proxy:0.0.1
    volumes:
      - ./wphdtfo-web-proxy/httpd_conf_custom:/usr/local/apache/conf/custom
    ports:
      - 80:80
    hostname: wphdtfo-web-proxy
    container_name: wphdtfo-web-proxy
    networks:
      - wphdtfo-net
    command:
      httpd-foreground
  wphdtfows-web-wsart-01:
    build:
      dockerfile: Dockerfile.wphdtfows-web
      context: .
    image: ilonghi/wphdtfows-web:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
    hostname: wphdtfows-web-wsart-01
    container_name: wphdtfows-web-wsart-01
    networks:
      - wphdtfo-net
    depends_on:
      - wphdtfo-memcached
    command:
      - /home/wphdtfows/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfows/WPHDTFO/etc/httpd.WSART.conf
      - -F
      - start
  wphdtfows-web-wsart-02:
    build:
      dockerfile: Dockerfile.wphdtfows-web
      context: .
    image: ilonghi/wphdtfows-web:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
    hostname: wphdtfows-web-wsart-02
    container_name: wphdtfows-web-wsart-02
    networks:
      - wphdtfo-net
    depends_on:
      - wphdtfo-memcached
    command:
      - /home/wphdtfows/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfows/WPHDTFO/etc/httpd.WSART.conf
      - -F
      - start
  wphdtfoui-web-restart-01:
    build:
      dockerfile: Dockerfile.wphdtfoui-web
      context: .
    image: ilonghi/wphdtfoui-web:0.0.1
    volumes:
      - ./WPHDTFOUI:/home/wphdtfo/WPHDTFOUI
      - ./COM:/home/wphdtfo/COM
    hostname: wphdtfoui-web-restart-01
    container_name: wphdtfoui-web-restart-01
    networks:
      - wphdtfo-net
    command:
      - /home/wphdtfo/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfo/WPHDTFOUI/etc/httpd.RESTART.conf
      - -F
      - start
  wphdtfoui-web-restart-02:
    build:
      dockerfile: Dockerfile.wphdtfoui-web
      context: .
    image: ilonghi/wphdtfoui-web:0.0.1
    volumes:
      - ./WPHDTFOUI:/home/wphdtfo/WPHDTFOUI
      - ./COM:/home/wphdtfo/COM
    hostname: wphdtfoui-web-restart-02
    container_name: wphdtfoui-web-restart-02
    networks:
      - wphdtfo-net
    command:
      - /home/wphdtfo/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfo/WPHDTFOUI/etc/httpd.RESTART.conf
      - -F
      - start
  wphdtfows-web-ivr-01:
    build:
      dockerfile: Dockerfile.wphdtfows-web
      context: .
    image: ilonghi/wphdtfows-web:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
      - wphdtfo-session-ivr:/home/wphdtfows/var/apache/session/IVR
    hostname: wphdtfows-web-ivr-01
    container_name: wphdtfows-web-ivr-01
    networks:
      - wphdtfo-net
    command:
      - /home/wphdtfows/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfows/WPHDTFO/etc/httpd.IVR.conf
      - -F
      - start
  wphdtfows-web-ivr-02:
    build:
      dockerfile: Dockerfile.wphdtfows-web
      context: .
    image: ilonghi/wphdtfows-web:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
      - wphdtfo-session-ivr:/home/wphdtfows/var/apache/session/IVR
    hostname: wphdtfows-web-ivr-02
    container_name: wphdtfows-web-ivr-02
    networks:
      - wphdtfo-net
    command:
      - /home/wphdtfows/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfows/WPHDTFO/etc/httpd.IVR.conf
      - -F
      - start
  wphdtfows-web-artlegacy-01:
    build:
      dockerfile: Dockerfile.wphdtfows-web
      context: .
    image: ilonghi/wphdtfows-web:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
      - wphdtfo-session-artlegacy:/home/wphdtfows/var/apache/session/ARTLEGACY
    hostname: wphdtfows-web-artlegacy-01
    container_name: wphdtfows-web-artlegacy-01
    networks:
      - wphdtfo-net
    command:
      - /home/wphdtfows/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfows/WPHDTFO/etc/httpd.ARTLEGACY.conf
      - -F
      - start
  wphdtfows-web-artlegacy-02:
    build:
      dockerfile: Dockerfile.wphdtfows-web
      context: .
    image: ilonghi/wphdtfows-web:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
      - wphdtfo-session-artlegacy:/home/wphdtfows/var/apache/session/ARTLEGACY
    hostname: wphdtfows-web-artlegacy-02
    container_name: wphdtfows-web-artlegacy-02
    networks:
      - wphdtfo-net
    command:
      - /home/wphdtfows/COM/bin/apachectl.sh
      - -C
      - /home/wphdtfows/WPHDTFO/etc/httpd.ARTLEGACY.conf
      - -F
      - start
  wphdtfo-web-phpmemcachedadmin:
    build:
      dockerfile: Dockerfile.wphdtfo-web-phpmemcachedadmin
      context: .
    image: ilonghi/wphdtfo-web-phpmemcachedadmin:0.0.1
    hostname: wphdtfo-web-phpmemcachedadmin
    container_name: wphdtfo-web-phpmemcachedadmin
    networks:
      - wphdtfo-net
  wphdtfows-oss-daemon-um:
    build:
      dockerfile: Dockerfile.wphdtfows-oss
      context: .
    image: ilonghi/wphdtfows-oss:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
    hostname: wphdtfows-oss
    container_name: wphdtfows-oss-daemon-um
    networks:
      - wphdtfo-net
    command:
      - /bin/bash
      - -c
      - source ~/.bash_profile; exec users_management --log-config=$${COM}/etc/users_management.docker.log4perl.conf --driver=API::ART::Driver::Users::JSON --oFile=$${ETC}/users.json --camelize-names --manage=C --manage=U --manage=D --notify-email=$${MAILADDR_BG} --daemon=30 --transaction-mode=c
  wphdtfows-oss-daemon-ac:
    build:
      dockerfile: Dockerfile.wphdtfows-oss
      context: .
    image: ilonghi/wphdtfows-oss:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
    hostname: wphdtfows-oss
    container_name: wphdtfows-oss-daemon-ac
    networks:
      - wphdtfo-net
    command:
      - /bin/bash
      - -c
      - source ~/.bash_profile; exec activity_count --daemon=30
  wphdtfows-oss-daemon-aes:
    build:
      dockerfile: Dockerfile.wphdtfows-oss
      context: .
    image: ilonghi/wphdtfows-oss:0.0.1
    volumes:
      - ./WPHDTFO:/home/wphdtfows/WPHDTFO
      - ./COM:/home/wphdtfows/COM
      - wphdtfo-art-repository-dsk:/home/wphdtfows/var/art_repository
      - wphdtfo-repository-dsk:/home/wphdtfows/var/repository
    hostname: wphdtfows-oss
    container_name: wphdtfows-oss-daemon-aes
    networks:
      - wphdtfo-net
    command:
      - /bin/bash
      - -c
      - source ~/.bash_profile; exec ramq --no-lock-file --log-config=$${COM}/etc/ramq.docker.log4perl.conf --daemon=30 --transaction-mode=c $${COM}/etc/ramq/API_ART/EmailService/ramq.conf

networks:
  wphdtfo-net:
    external:
      name: wphdtfo-net

volumes:
  wphdtfo-art-repository-dsk:
    external: true
    name: wphdtfo-art-repository-dsk
  wphdtfo-repository-dsk:
    external: true
    name: wphdtfo-repository-dsk
  wphdtfo-session-ivr:
    external: true
    name: wphdtfo-session-ivr
  wphdtfo-session-artlegacy:
    external: true
    name: wphdtfo-session-artlegacy
